name: Generate signals record

on:
  schedule:
    - cron: "*/15 * * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  TZ: Europe/Berlin

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1

      - name: Build
        run: |
          poetry install
          poetry run python build.py

      - uses: stefanzweifel/git-auto-commit-action@v5
