name: Generate signals record

on:
  schedule:
    - cron: "*/15 * * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  TZ: Europe/Berlin

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    services:
      ib-gateway:
        image: ghcr.io/gnzsnz/ib-gateway:stable
        env:
          TWS_USERID: ${{ secrets.TWS_USERID }}
          TWS_PASSWORD: ${{ secrets.TWS_PASSWORD }}
          TRADING_MODE: paper
          READ_ONLY_API: no
        ports:
          - 127.0.0.1:4002:4004
        options: >-
          --health-cmd "nc -z localhost 4004 || exit 1"
          --health-interval 5s
          --health-timeout 20s
          --health-retries 100
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Setup poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.2.1

      - name: Build
        run: |
          poetry install
          poetry run python main.py

      - uses: stefanzweifel/git-auto-commit-action@v7
